### PR TITLE
Updated dates for 2022

### PR DESCRIPTION
**Pull request by nlharris**
Would appreciate review in case I messed anything up!

### CODE REVIEW

**Comment by nlharris** [comment]
@JasonJWilliamsNY I don't seem to be able to add you as a suggested reviewer because you're not in the OBF org but please take a look if you have time! Thanks!

**Comment by peterjc** [comment]
I didn't confirm any of the timeline dates with ISCB information, but otherwise the 2021 to 2022 and Code of Conduct changes look good.

**Comment by khokamp** [comment]
Hi,

According to https://www.iscb.org/ismb2022-key-dates
Abstracts Submission opens on Monday, January 24, 2022 (not February 2022)

The rest looks good.

Karsten

**Comment by nlharris** [comment]
Shoot, Jan 24, that's soon! 😯
Thanks for reviewing -- I'll fix that.

**Pull request merged**
